#!/bin/sh
#
# https://github.com/remsnet/xen-tools


prefix=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

#
#  Update yum lists.
#
chroot ${prefix} yum -y update

#
#  Install the packages
#
installRPMPackage ${prefix} perl python
installRPMPackage ${prefix} samba samba-client samba-doc samba-swat cifs-utils
installRPMPackage ${prefix} ctdb
#
