#!/bin/sh
#
# This script sets up the owncloud repro for Yum on centos
#see http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud

# https://github.com/remsnet/xen-tools
#set -x

prefix=$1


#
# Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update yum
#

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


if [ ! -d ${prefix}/etc/yum.repos.d ]; then
    mkdir -p ${prefix}/etc/yum.repos.d
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/yum -y install wget

cd  ${prefix}/etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:community/CentOS_CentOS-6/isv:ownCloud:community.repo


chroot ${prefix} /usr/bin/yum -y update

umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f ${prefix}/dev

#
# Log our finish
#
logMessage Script $0 finished
