#!/bin/sh
#
#  This script sets up the pkgs.org repro  for Yum  onCentOS
# http://www.thegeekstuff.com/2012/06/enable-epel-repository/
# http://ftp-stud.hs-esslingen.de/pub/epel/6/i386/repoview/epel-release.html


# https://github.com/remsnet/xen-tools
#set -x

prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update yum
#

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


if [ ! -d ${prefix}/etc/yum.repos.d ]; then
    mkdir -p ${prefix}/etc/yum.repos.d
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/yum -y install wget

# epel standard v 6.8
chroot ${prefix} mkdir -p /var/tmp
chroot ${prefix} wget http://ftp-stud.hs-esslingen.de/pub/epel/6/i386/epel-release-6-8.noarch.rpm -o  /var/tmp/epel-release-6-8.noarch.rpm
chroot ${prefix} rpm -U --force /var/tmp/epel-release-6-8.noarch.rpm
chroot ${prefix} rm -f /var/tmp/epel-release-6-8.noarch.rpm

# epel nux 
cat >>${prefix}/etc/yum.repos.d/pkg.org-nux-misc.repo << EOF
[nux-misc]
name=Nux Misc
baseurl=http://li.nux.ro/download/nux/misc/el6/x86_64/
enabled=0
gpgcheck=1
gpgkey=http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
#
EOF

chroot ${prefix} /usr/bin/yum -y  update

umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev

#
#  Log our finish
#
logMessage Script $0 finished
