#!/bin/sh
#
#  This script sets up the zypper on OpenSuSE 13.1
#
# https://github.com/remsnet/xen-tool

prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update zypper
#

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mcunt -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper -v  refresh
chroot ${prefix} /usr/bin/zypper -v  update --force --auto-agree-with-licenses
#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev

#
#  Log our finish
#
logMessage Script $0 finished
