#!/bin/sh
#
#  This script installs the GRUB software bevor the kernel...
#
# https://github.com/remsnet/xen-tools

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#
# Log our start
#
logMessage Script $0 starting

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper --non-interactive  install grub binutils mkinitrd perl-Bootloader perl-XML-Parser


if [ ! -d ${prefix}/boot/grub ]; then
        mkdir -p ${prefix}/boot/grub
fi

#
# create device.map
test -f ${prefix}/boot/grub/device.map && mv -f  ${prefix}/boot/grub/device.map  ${prefix}/boot/grub/device.map.old
echo "(hd0)   /dev/xvda" > ${prefix}/boot/grub/device.map

# create default grub.conf
test -f ${prefix}/etc/grub.conf && mv -f  ${prefix}/etc/grub.conf ${prefix}/etc/grub.conf.old
echo 'setup --stage2=/boot/grub/stage2 --force-lba (hd0,0) (hd0,0)' >${prefix}/etc/grub.conf
#

umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev



#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev



#
#  Log our finish
#
logMessage Script $0 finished
