#!/bin/sh
#
#  this script installs an simple initramfs to allow overcome OSS devtmpfs issues with OSS kernel-xen
#
#  customize it on your own needs.
#
# https://github.com/remsnet/xen-tools


prefix=$1


#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


# Log our start
#
logMessage Script $0 starting

mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper --non-interactive install psmisc busybox-static
#

# Install copy of mkinitramfs tool from https://github.com/remsnet/OpenSuSE-initramfs
#
test -d ${prefix}/sbin || mkdir -p ${prefix}/sbin
test -d ${prefix}/usr/share/mkinitramfs || mkdir -p ${prefix}/usr/share/mkinitramfs
#
# install busybox-static based mkBusyBoxinitramfs
test -d /etc/xen-tools/initramfs || mkdir -p /etc/xen-tools/initramfs
install -m 755 /etc/xen-tools/initramfs/mkBusyBoxinitramfs ${prefix}/sbin/mkBusyBoxinitramfs

# installs the initramfs init template
test -d ${prefix}/usr/share/mkinitramfs || mkdir -p  ${prefix}/usr/share/mkinitramfs
install -m 755 /etc/xen-tools/initramfs/BusyBoxramfs.init ${prefix}/usr/share/mkinitramfs/BusyBoxramfs.init 

chroot ${prefix} chmod 0755 /sbin/mkBusyBoxinitramfs /usr/share/mkinitramfs/BusyBoxramfs.init
#
#  Log our finish
#
logMessage Script $0 finished
[root@ex40 opensuse-13.1.d]#
