#!/bin/sh
#
#  this script installs an simple initramfs to allow overcome OSS devtmpfs issues with OSS kernel-xen
#
#  customize it on your own needs.
#
# https://github.com/remsnet/xen-tools


prefix=$1


#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


# Log our start
#
logMessage Script $0 starting

mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper --non-interactive install psmisc
#

# Install copy of mkinitramfs tool from https://github.com/remsnet/OpenSuSE-initramfs
#
test -d ${prefix}/sbin || mkdir -p ${prefix}/sbin
test -d ${prefix}/usr/share/mkinitramfs || mkdir -p ${prefix}/usr/share/mkinitramfs
#
cat >>${prefix}//sbin/mkinitramfs << EOF
#!/bin/sh
#
# file : /sbin/mkinitramfs
# part of https://github.com/remsnet/OpenSuSE-initramfs
#
# v0.1.4  - 22 june 2014
# Author : Remsnet Consulting & internet Services LTD
#          horst.venzke@remsnet.de
# License : LGPL v2


# ENV
KERNEL_VERSION=`ls /boot/vmlinuz-* | xargs | awk -F " " '{ print $1 }' | sed "s#/boot/vmlinuz-##"`
BOOT=/boot
INITRAMFS_FILE=$BOOT/initramfs.img-$KERNEL_VERSION
DATADIR=/usr/share/mkinitramfs
INITIN=init.in
CPIOBIN=/usr/bin/cpio
GZIPBIN=/usr/bin/gzip
PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin
export PATH

WDIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)
unsorted=$(mktemp /tmp/unsorted.XXXXXXXXXX)
binfiles="sh bzip2 flock mkfifo cat cp dd killall ls  mkdir mknod mount umount sed awk chgrp chown chmod env base64 cat chattr grep  id free last dmesg bzcat zcat chroot less sleep ln rm uname pkill"
sbinfiles="modprobe udevadm blkid rmmod blockdev dmeventd dmsetup losetup mdadm reboot pidof killall5 lvm switch_root mdadm mdmon cryptsetup udevd udevadm lspci fsck fsck.ext3 fsck.xfs"

userbinfiles=""
usersbinfiles="useradd userdel groupadd groupdel groupmod usermod partx"

# we log what happen - xen-tools 24-setup-initramfs autoinstall hook
test -d /var/log/xen-tools || mkdir -p /var/log/xen-tools/
touch /var/log/xen-tools/initramfs.log

# functions
function copy() {

       test -r $1 &&  cp -fp $1 $2  >> /var/log/xen-tools/initramfs.log 2>&1
}

function copyall() {

       test -r $1 &&  cp -rfp $1 $2 >> /var/log/xen-tools/initramfs.log 2>&1
}

function cleanup() {
# cleanup workdir and unsorted
        rm -rf $WDIR $unsorted
}

function make_initramfs() {

( cd $WDIR ; find . | $CPIOBIN -o -H newc --quiet | $GZIPBIN -9 ) > $INITRAMFS_FILE

}

if [ -n "$KERNEL_VERSION" ] && [ ! -d "/lib/modules/$1" ] ; then
  echo "No modules directory named $1"
  exit 1
fi

function msg_start(){
printf "Creating $INITRAMFS_FILE... "
printf " \n \n"
}

function msg_end(){
printf "Creating $INITRAMFS_FILE completed..."
printf " \n \n"
}



# Systemd installs udevadm in /bin. Other udev implementations have it in /sbin
msg_start
#
if [ -x /sbin/udevadm ] ; then binfiles="$binfiles"; fi


# Create base directory structure
mkdir -p $WDIR/{bin,dev,lib/firmware,run,sbin,sys,proc,usr/share/mkinitramfs}
mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}

touch $WDIR/etc/modprobe.d/modprobe.conf
ln -s lib $WDIR/lib64
cd usr
 ln -s ../bin bin
 ln -s ../sbin sbin
 ln -s ../lib lib
cd

#  Create newroot
mkdir newroot

# Create necessary device nodes
mknod -m 640 $WDIR/dev/console c 5 1
mknod -m 640 $WDIR/dev/random c 1 8
mknod -m 640 $WDIR/dev/urandom c 1 9
mknod -m 664 $WDIR/dev/null    c 1 3
mknod -m 664 $WDIR/dev/zero    c 1 5
mknod -m 664 $WDIR/dev/tty     c 5 0
mknod -m 664 $WDIR/dev/tty1    c 4 1
mknod -m 664 $WDIR/dev/vcs     c 7 0
mknod -m 664 $WDIR/dev/vcsa    c 7 128
mknod -m 664 $WDIR/dev/xvda    b 202 0
mknod -m 664 $WDIR/dev/loop0   b 7 0

# Install the udev configuration files
if [ -f /etc/udev/udev.conf ]; then
  copy /etc/udev/udev.conf $WDIR/etc/udev/udev.conf
fi

for file in $(find /etc/udev/rules.d/ -type f) ; do
  copy $file $WDIR/etc/udev/rules.d
done

# Install any firmware present
 copyall /lib/firmware $WDIR/lib

# Copy the RAID configuration file if present
if [ -f /etc/mdadm.conf ] ; then
  copy /etc/mdadm.conf $WDIR/etc
fi

# Install the init file
install -m0755 $DATADIR/$INITIN $WDIR/init

if [  -n "$KERNEL_VERSION" ] ; then
  if [ -x /usr/bin/kmod ] ; then
    binfiles="$binfiles kmod"
  else
    binfiles="$binfiles lsmod"
    sbinfiles="$sbinfiles insmod"
  fi
fi

# Install basic binaries
for f in $binfiles ; do
  ldd /usr/bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f $WDIR/usr/bin
done

# Add lvm if present
if [ -x /sbin/lvm ] ; then sbinfiles="$sbinfiles lvm dmsetup"; fi

for f in $sbinfiles ; do
  ldd /sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f $WDIR/sbin
done

# some files moved - Linux standard base - v3.0
for f in $usersbinfiles ; do
  ldd /usr/sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f $WDIR/usr/sbin
done

# Add udevd libraries if not in /sbin
if [ -x /lib/udev/udevd ] ; then
  ldd /lib/udev/udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
elif [ -x /lib/systemd/systemd-udevd ] ; then
  ldd /usr/lib/systemd/systemd-udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
fi

# Add module symlinks if appropriate
if [ -n "$KERNEL_VERSION" ] && [ -x /usr/bin/kmod ] ; then
  ln -s kmod $WDIR/bin/lsmod
  ln -s kmod $WDIR/bin/insmod
fi

# Add lvm symlinks if appropriate
# Also copy the lvm.conf file
if  [ -x /sbin/lvm ] ; then
  ln -s lvm $WDIR/sbin/lvchange
  ln -s lvm $WDIR/sbin/lvrename
  ln -s lvm $WDIR/sbin/lvextend
  ln -s lvm $WDIR/sbin/lvcreate
  ln -s lvm $WDIR/sbin/lvdisplay
  ln -s lvm $WDIR/sbin/lvscan

  ln -s lvm $WDIR/sbin/pvchange
  ln -s lvm $WDIR/sbin/pvck
  ln -s lvm $WDIR/sbin/pvcreate
  ln -s lvm $WDIR/sbin/pvdisplay
  ln -s lvm $WDIR/sbin/pvscan

  ln -s lvm $WDIR/sbin/vgchange
  ln -s lvm $WDIR/sbin/vgcreate
  ln -s lvm $WDIR/sbin/vgscan
  ln -s lvm $WDIR/sbin/vgrename
  ln -s lvm $WDIR/sbin/vgck
  # Conf file(s)
  copyall /etc/lvm $WDIR/etc
fi

# Install libraries
sort $unsorted | uniq | while read library ; do
  if [ "$library" == "linux-vdso.so.1" ] ||
     [ "$library" == "linux-gate.so.1" ]; then
    continue
  fi

  copy $library $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
done

if [ -d /lib/udev ]; then
  copyall /lib/udev $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
fi
if [ -d /lib/systemd ]; then
  copyall /lib/systemd $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
fi

# Install the kernel modules if requested
if [ -n "$KERNEL_VERSION" ]; then
  find                                                                        \
     /lib/modules/$KERNEL_VERSION/kernel/{crypto,fs,lib}                      \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/{block,ata,md}      \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/{scsi,message,xen,block,virtio,base,rtc} \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/usb/{host,storage}           \
     -type f 2> /dev/null | cpio --make-directories -p --quiet $WDIR >> /var/log/xen-tools/initramfs.log 2>&1

  copy /lib/modules/$KERNEL_VERSION/modules.{builtin,order}                     \
            $WDIR/lib/modules/$KERNEL_VERSION >> /var/log/xen-tools/initramfs.log 2>&1

  depmod -b $WDIR $KERNEL_VERSION >> /var/log/xen-tools/initramfs.log 2>&1
fi

# make the initramfs
make_initramfs >> /var/log/xen-tools/initramfs.log 2>&1

# Remove the temporary directory and file
cleanup

msg_end
#
# EOF
EOF

cat >>${prefix}/usr/share/mkinitramfs/init.in << EOF
#!/bin/sh

#
# file : /usr/share/mkinitramfs/init.in
# part of https://github.com/remsnet/OpenSuSE-initramfs
#
# v0.1.4  - 22 june 2014
# Author : Remsnet Consulting & internet Services LTD
#          horst.venzke@remsnet.de
# License : LGPL v2


PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH

problem()
{
   printf "Encountered a problem!\n\nDropping you to a shell.\n\n"
   sh
}

no_device()
{
   printf "The device %s, which is supposed to contain the\n" $1
   printf "root file system, does not exist.\n"
   printf "Please fix this problem and exit this shell.\n\n"
}

no_mount()
{
   printf "Could not mount device %s\n" $1
   printf "Sleeping forever. Please reboot and fix the kernel command line.\n\n"
   printf "Maybe the device is formatted with an unsupported file system?\n\n"
   printf "Or maybe filesystem type autodetection went wrong, in which case\n"
   printf "you should add the rootfstype=... parameter to the kernel command line.\n\n"
   printf "Available partitions:\n"
}

do_mount_root()
{
   mkdir /.root
   [ -n "$rootflags" ] && rootflags="$rootflags,"
   rootflags="$rootflags$ro"

   case "$root" in
      /dev/* ) device=$root ;;
      UUID=* ) eval $root; device="/dev/disk/by-uuid/$UUID"  ;;
      LABEL=*) eval $root; device="/dev/disk/by-label/$LABEL" ;;
      PATH=*) eval $root; device="/dev/disk/by-path/$PATH" ;;
      ""     ) echo "No root device specified." ; problem    ;;
   esac

   while [ ! -b "$device" ] ; do
       no_device $device
       problem
   done

   if ! mount -n -t "$rootfstype" -o "$rootflags" "$device" /.root ; then
       no_mount $device
       cat /proc/partitions
       while true ; do sleep 10000 ; done
   else
       echo "Successfully mounted device $root"
   fi
}

init=/sbin/init
root=
rootdelay=
rootfstype=auto
ro="ro"
rootflags=
device=

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

read -r cmdline < /proc/cmdline

for param in $cmdline ; do
  case $param in
    init=*      ) init=${param#init=}             ;;
    root=*      ) root=${param#root=}             ;;
    rootdelay=* ) rootdelay=${param#rootdelay=}   ;;
    rootfstype=*) rootfstype=${param#rootfstype=} ;;
    rootflags=* ) rootflags=${param#rootflags=}   ;;
    ro          ) ro="ro"                         ;;
    rw          ) ro="rw"                         ;;
  esac
done

# udevd location depends on version
if [ -x /sbin/udevd ]; then
  UDEVD=/sbin/udevd
elif [ -x /lib/udev/udevd ]; then
  UDEVD=/lib/udev/udevd
elif [ -x /lib/systemd/systemd-udevd ]; then
  UDEVD=/lib/systemd/systemd-udevd
else
  echo "Cannot find udevd nor systemd-udevd"
  problem
fi

${UDEVD} --daemon --resolve-names=never
udevadm trigger
udevadm settle

if [ -f /etc/mdadm.conf ] ; then mdadm -As                       ; fi
if [ -x /sbin/vgchange  ] ; then /sbin/vgchange -a y > /dev/null ; fi
if [ -n "$rootdelay"    ] ; then sleep "$rootdelay"              ; fi

do_mount_root

killall -w ${UDEVD##*/}

# Unmount everything else you've attached to rootfs.  (Moving the filesystems
# into newroot is something useful to do with them.)

mount --move /sys /newroot/sys
mount --move /proc /newroot/proc
mount --move /dev /newroot/dev
mount --move /run /newroot/var/run

# Now switch to the new filesystem, and run /sbin/init out of it.  Don't
# forget the "exec" here, because you want the new init program to inherit
# PID 1.


exec switch_root /.root "$init" "$@"
EOF

chroot ${prefix} /usr/bin/chmod 0755 /sbin/mkinitramfs; /usr/bin/chown 0:0 /sbin/mkinitramfs
chroot ${prefix} /usr/bin/chmod 0755 /sbin/init; /usr/bin/chown 0:0 /sbin/init

#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev


#
#  Log our finish
#
logMessage Script $0 finished
