#!/bin/sh
#
#  This script sets up the kernel and fstab for OpenSuSE 13.1
#
# https://github.com/remsnet/xen-tools

prefix=$1

#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi

#
# Log our start
#
logMessage Script $0 starting

# Make the console work
sed -i "/Cancelled/ {G;s/$/co:2345:respawn:\/sbin\/mingetty console/;}" ${prefix}/etc/inittab
sed -i "s/^1:2345/#1:2345/" ${prefix}/etc/inittab

# MAKEDEV is needed at this point
chroot ${prefix} zypper --non-interactive install makedev
chroot ${prefix} ln -s /sbin/MAKEDEV /dev/MAKEDEV
chroot ${prefix} /sbin/MAKEDEV sda sdb sdc sdd

# Create fstab
logMessage Create /etc/fstab
cat > ${prefix}/etc/fstab << EOF
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
#
proc            /proc           proc    defaults        0       0
none            /dev/pts        devpts  mode=0620       0       0
#
EOF

for i in `seq 1 $NUMPARTITIONS`; do
  echo -n "/dev/sda$i " >> ${prefix}/etc/fstab
  eval part=\$PARTITION$i
  if [ -n "`echo $part | grep swap`" ]; then
     echo "none swap ws 0 0" >> ${prefix}/etc/fstab
  else
     echo $part | awk -F: '{print $4,$3,$5,0,1}' >> ${prefix}/etc/fstab
  fi
done


# Install the kernel, grub and perl
chroot ${prefix} zypper clean expire-cache
#

# oss specific : PBL_SKIP_BOOT_TEST reqired if /boot been not an mount
chroot  ${prefix} test -x  /etc/profile.d/boot_pbl_skip_boot.sh || echo "export PBL_SKIP_BOOT_TEST=1" >/etc/profile.d/boot_pbl_skip_boot.sh; chmod 750 /etc/profile.d/boot_pbl_skip_boot.sh



# prepare to install lastest stable oss13.1 +3.11 kernel-xen
chroot ${prefix} cd /etc/zypp/repos.d/; wget http://download.opensuse.org/repositories/Kernel:/openSUSE-13.1/standard/Kernel:openSUSE-13.1.repo
chroot ${prefix} zypper ref

# prepare to install lastest unstable +3.15 kernel-xen
#chroot ${prefix} cd /etc/zypp/repos.d/; wget http://download.opensuse.org/repositories/Kernel:/HEAD/standard/Kernel:HEAD.repo
#chroot ${prefix} zypper ref


#
# debug avalible kernel pkgs .. outputs to xen logfile
#
chroot ${prefix} zypper --non-interactive install perl-Bootloader perl-XML-Parser
chroot ${prefix} zypper --non-interactive install kernel-xen  grub2 kernel-firmware dracut-tools kmod-compat mkinitrd
chroot ${prefix} zypper --non-interactive update

KERNELVERSION=`ls ${prefix}/boot/vmlinuz-* | xargs | awk -F " " '{ print $1 }' |sed "s#$prefix/boot/vmlinuz-##"`
logMessage "Kernel $KERNELVERSION found"

# Create grub's menu.list
logMessage "Creating /boot/grub2/menu.lst"

if [ ! -d ${prefix}/boot/grub2 ]; then
        mkdir -p ${prefix}/boot/grub2
fi

cat > ${prefix}/boot/grub2/menu.lst << EOF
# WARNING : Don't forget to update this when you upgrade kernel !
# You can also exclude kernel-xen from updates by putting
# exclude=kernel-xen in in [main] in zypper.conf

default=0
timeout=5
title OpenSuSE  x86_64 13.1 ($KERNELVERSION) Paravirtual Guest
kernel        /boot/vmlinuz-$KERNELVERSION elevator=noop console=tty0 console=hvc0 noresume selinux=0
initrd        /boot/initrd-$KERNELVERSION
EOF

# Some use lvm but mkinitrd will generate a wrong initrd when these are present.
rm -f ${prefix}/etc/lvm/backup/* ${prefix}/etc/lvm/archive/*

if [ ! -d ${prefix}/etc/initramfs-tools/conf.d/ ]; then
mkdir -p ${prefix}/etc/initramfs-tools/conf.d/
fi

if [ ! -f ${prefix}/etc/initramfs-tools/conf.d/xen-modules ]; then
echo "MODULES=xenblk xennet xen_blkfront xenfs xen-netfront" >$prefix/etc/initramfs-tools/conf.d/xen-modules
fi

mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev

chroot ${prefix} grub2-mkconfig -o /boot/grub2/grub.cfg
chroot ${prefix} dracut -f  --add-drivers "xenblk xennet xen_blkfront xenfs xen-netfront xfs lvm2"

umount -f  ${prefix}/proc
umount -f  ${prefix}/sys
umount -f  ${prefix}/dev



#
#  Log our finish
#
logMessage Script $0 finished
