#!/bin/sh
#
#  This script sets up the expect  for Opensuse 13.1
#  required to set the root passwd with expect chat automated

# https://github.com/remsnet/xen-tools


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
# Update zypper
#

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper --non-interactive  install expect
#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev

#
#  Log our finish
#
logMessage Script $0 finished
