#!/bin/sh
#
#  This role install systemd runevel 3
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#
# Log our start
#
logMessage Script $0 starting

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi

if [ ! -d ${prefix}/etc/sysctl.d ]; then
    mkdir -p ${prefix}/etc/sysctl.d
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#

chroot ${prefix} test -e /etc/systemd/system/default.target && rm -f /etc/systemd/system/default.target
chroot ${prefix} ln -sf /usr/lib/systemd/system/multi-user.target /etc/systemd/system/default.target
#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev


#
#  Log our finish
#
logMessage Script $0 finished
#
