#!/bin/sh
#
#  This script sets up the networking files for OpenSuSE 13.1
# this is an complete core network rewire and differ from other distributions in many details.
#
# https://github.com/remsnet/xen-tools


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Make sure we have an /etc/sysconfig/network directory - required by network scripts
#
if [ ! -d ${prefix}/etc/sysconfig/network/ ]; then
  mkdir -p ${prefix}/etc/sysconfig/network/
fi

#  Make sure we have an /var/run/netreport - required by network-functions
if [ ! -d ${prefix}/var/run/netreport ]; then
mkdir -p ${prefix}/var/run/netreport
fi

## setup devaliases
echo "alias eth0 xennet" > ${prefix}/etc/modprobe.d/10-xen.conf
echo "alias eth1 xennet" >> ${prefix}/etc/modprobe.d/10-xen.conf


echo "dhcp value" ${dhcp}

#
#  Test for static vs. DHCP
#
if [ ! -z "${dhcp}" ]; then

    #
    #  Setup the initial interface
    #
    cat <<E_O_STATIC >${prefix}/etc/sysconfig/network/ifcfg-eth0
STARTMODE='auto'
NAME='eth0'
ETHTOOL_OPTIONS=''
BOOTPROTO='static'
IPADDR=$ip1/$maskbits
NETWORK=$network
MTU=''
BROADCAST=$broadcast
REMOTE_IPADDR=''
USERCONTROL='no'
#
E_O_STATIC

     #
     #  Now setup any other ones.
     #
     interface=1
     count=2

     while [ "${count}" -le "${ip_count}" ]; do

         value=\$ip${count}
         value=`eval echo $value`

         logMessage Adding eth${interface}

         cat <<E_O_STATIC >${prefix}/etc/sysconfig/network/ifcfg-eth${interface}
STARTMODE='auto'
NAME=eth$interface
ONBOOT=yes
MTU=''
BOOTPROTO=static
IPADDR=$value/$maskbits
NETWORK=$network
BROADCAST=$broadcast
REMOTE_IPADDR=''
USERCONTROL='no'
#
E_O_STATIC
         count=`expr $count + 1`
         interface=`expr $interface + 1`
     done

    #
    # Hooks are run chrooted, hence the resolv.conf is moved
    # temporarily to /etc/resolv.conf.old. Use that file, it
    # will be restored after hooks are run.
    #
    if [ '' != "$nameserver" ]; then
        rm -f ${prefix}/etc/resolv.conf.old
        for ns in $nameserver; do
            echo "nameserver $ns" >>${prefix}/etc/resolv.conf.old
        done
    else
        cp /etc/resolv.conf ${prefix}/etc/resolv.conf.old
    fi
else
    cat <<E_O_DHCP >${prefix}/etc/sysconfig/network/ifcfg-eth0
STARTMODE='auto'
NAME=eth0
BOOTPROTO=dhcp
USERCONTROL='no'
#
E_O_DHCP
    chroot ${prefix} /usr/bin/zypper --non-interactive install dhcpcd
fi

#
# SuSE stype : setup the default route.
echo "default" ${gateway} "- -"  >${prefix}/etc/sysconfig/network/routes


# add hostname to /etc/hosts
echo "$ip1" "$hostname" >>"$prefix"/etc/hosts

#
#--------------------------------------------
ntpserver="$nameserver"
dnssearch='softwareenergie.eu softwareenergie.de softwareenergie.at ads.softwareenergie.eu remsnet.net'

# parse config file
conf="$prefix"/etc/sysconfig/network/config
cp "$conf" "$conf"-orig
sed '
	/^NETCONFIG_DNS_STATIC_SERVERS=/ {
		s/=.*/="'"$nameserver"'"/
	}
	/^NETCONFIG_NTP_STATIC_SERVERS=/ {
		s/=.*/="'"$ntpserver"'"/
	}
	/^NETCONFIG_DNS_STATIC_SEARCHLIST=/ {
		s/=.*/="'"$dnssearch"'"/
	}
	/^NOZEROCONF=/ {
		s/=.*/="yes"/
	}
' "$conf"-orig > "$conf"

#
#  Log our finish
#
logMessage Script $0 finished
