#!/bin/sh
#
#  This script ensures that the new guest images have a nicely
# populated /dev directory.

# https://github.com/remsnet/xen-tools/


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
# Test where MAKEDEV is located, assuming /sbin/ as default
#
MAKEDEV=''
MAKEDEV_PATHS="/sbin/MAKEDEV /dev/MAKEDEV"
for MAKEDEV_PATH in ${MAKEDEV_PATHS}; do
    if [ -x "${prefix}${MAKEDEV_PATH}" ]; then
    MAKEDEV="${prefix}${MAKEDEV_PATH}"
    break
    fi
done

# MAKEDEV is needed at this point
chroot ${prefix} zypper --non-interactive install makedev
chroot ${prefix} ln -s /sbin/MAKEDEV /dev/MAKEDEV


for i in std hda sda sdb sdc sdd tty tty1 tty2 tty3 tty4 tty5 tty6 tty7 tty8 console null zero ram mem kmsg rtc
        do
        chroot ${prefix}  /bin/bash -c cd /dev; /sbin/MAKEDEV  $i
        done

for i in xvda xvda1 xvda2 xvda3 xvda4 xvda5 xvda6
        do
                 chroot ${prefix}  /bin/bash -c mknod /dev/$i 202 0
        done



#
#  Log our finish
#
logMessage Script $0 finished
