#!/bin/sh
#
#  This script ensures that the new guest images have a nicely
# populated /dev directory.
#
# Steve
# --
# http://www.steve.org.uk/


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
# Test where MAKEDEV is located, assuming /sbin/ as default
#
MAKEDEV=''
MAKEDEV_PATHS="/sbin/MAKEDEV /dev/MAKEDEV"
for MAKEDEV_PATH in ${MAKEDEV_PATHS}; do
    if [ -x "${prefix}${MAKEDEV_PATH}" ]; then
    MAKEDEV="${prefix}${MAKEDEV_PATH}"
    break
    fi
done

if [ -n "${MAKEDEV}" ]; then

#
# Early termination if we have a couple of common devices present
# should speed up installs which use --copy/--tar
#
if ( test `ls -1 ${prefix}/dev | wc -l` -gt 10 ); then
    #
    # We still need to make sure the basic devices are present
    #
    cd ${prefix}/dev
    ${MAKEDEV} std
    ${MAKEDEV} hda
    ${MAKEDEV} sda
    ${MAKEDEV} tty1

    logMessage "Terminating because there appear to be files in /dev already"
    exit
fi


#
#  Make the device nodes.
#
cd ${prefix}/dev
${MAKEDEV} generic
${MAKEDEV} std

fi # -n ${MAKEDEV}

#
#  Log our finish
#
logMessage Script $0 finished
[root@ex40 opensuse-13.1.d]# cat 55-create-dev^C
[root@ex40 opensuse-13.1.d]# ls
02-setup-temp    25-generate-locale   29-setup-ntp       40-setup-networking  70-install-ssh      91-fix-subsys
10-disable-tls   26-setup-kernel      30-disable-gettys  50-setup-hostname    75-fixup-securetty  92-setup-yast
15-setup-arch    28-setup-nrpe        31-setup-sudo      55-create-dev        85-block-attach     99-clean-image
20-setup-zypper  29-setup-bind-utils  31-setup-sysctl    65-copy-user-files   90-make-fstab
[root@ex40 opensuse-13.1.d]# cat 65-copy-user-files
#!/bin/sh
#
#  Copy files from a 'skel' directory, if present, into the
# new images
#


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting


#
#  Copy everything from the skel directory into the new instance
# if that directory exists.
#
if [ -d /etc/xen-tools/skel ]; then

    logMessage Copying files from /etc/xen-tools/skel

    (cd /etc/xen-tools/skel; tar -cf - . ) | (cd ${prefix}/; tar -xpf -)

    logMessage Finished

else

    logMessage skel directory, /etc/xen-tools/skell, not present ignoring.

fi


#
#  Log our finish
#
logMessage Script $0 finished
