#!/bin/sh
#
#  This script sets up the Yast2 for OpenSuSE 13.1
#
# https://github.com/remsnet/xen-tools


prefix=$1


#
#  Source our common functions
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    . ./hooks/common.sh
fi


#
# Log our start
#
logMessage Script $0 starting

#
# Update zypper
#

if [ ! -d ${prefix}/proc ]; then
    mkdir -p ${prefix}/proc
fi
if [ ! -d ${prefix}/sys ]; then
    mkdir -p ${prefix}/sys
fi

if [ ! -d ${prefix}/dev ]; then
    mkdir -p ${prefix}/dev
fi


mount -o bind /proc ${prefix}/proc
mount -o bind /sys ${prefix}/sys
mount -o bind /dev ${prefix}/dev
#
chroot ${prefix} /usr/bin/zypper --non-interactive ref
#
chroot ${prefix} /usr/bin/zypper --non-interactive install yast2-online-update yast2-online-update-configuration yast2-online-update-frontend
chroot ${prefix} /usr/bin/zypper --non-interactive install patterns-openSUSE-yast2_basis yast2-inetd yast2-network yast2-storage yast2-sysconfig yast2-trans yast2-sudo yast2-runlevel yast2-pam
chroot ${prefix} /usr/bin/zypper --non-interactive install yast2-trans-de yast2-trans-en_GB yast2-proxy yast2-ntp-client
#
chroot ${prefix} /usr/bin/zypper --non-interactive update
#
umount -f ${prefix}/proc
umount -f ${prefix}/sys
umount -f  ${prefix}/dev

#
#  Log our finish
#
logMessage Script $0 finished
